#!/usr/bin/env python
from kafka import KafkaProducer
import json
import threading
import time

generater = KafkaProducer(bootstrap_servers='localhost:9092', value_serializer=lambda v: json.dumps(v).encode('utf-8'))
generater.send('syslog', {'name' : 'test', 'alarm': 'packet-drop'})



